--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=game:GetService("Players");local v1=game:GetService("RunService");local v2=game:GetService("TeleportService");local v3=game:GetService("Lighting");local v4=v0.LocalPlayer;local v5=v4.Character or v4.CharacterAdded:Wait() ;local v6=v5:WaitForChild("HumanoidRootPart");local v7=0 -0 ;local v8=60;local v9=v6.Position;v1.Heartbeat:Connect(function(v18) if ((v6.Position-v9).magnitude<(931.1 -(857 + 74))) then local v24=568 -(367 + 201) ;while true do if (v24==0) then v7=v7 + v18 ;if (v7>=v8) then v2:Teleport(game.PlaceId,v4);end break;end end else v7=927 -(214 + 713) ;v9=v6.Position;end end);for v19,v20 in pairs(workspace:GetDescendants()) do if (v20:IsA("Part") or v20:IsA("UnionOperation") or v20:IsA("MeshPart")) then local v26=0;while true do if (v26==0) then v20.Material=Enum.Material.SmoothPlastic;v20.Reflectance=0 + 0 ;break;end end elseif (v20:IsA("Decal") or v20:IsA("Texture") or v20:IsA("SurfaceAppearance")) then v20.Transparency=1 + 0 ;elseif (v20:IsA("ParticleEmitter") or v20:IsA("Trail")) then v20.Enabled=false;end end settings().Rendering.QualityLevel=Enum.QualityLevel.Level01;workspace.FallenPartsDestroyHeight= -500;if workspace:FindFirstChild("Terrain") then local v22=877 -(282 + 595) ;while true do if (v22==(1638 -(1523 + 114))) then workspace.Terrain.WaterReflectance=0 + 0 ;workspace.Terrain.WaterTransparency=1 -0 ;break;end if (v22==(1065 -(68 + 997))) then workspace.Terrain.WaterWaveSize=1270 -(226 + 1044) ;workspace.Terrain.WaterWaveSpeed=0 -0 ;v22=118 -(32 + 85) ;end end end v3.GlobalShadows=false;v3.FogEnd=9000000741 -(976 + 277) ;v3.Brightness=957 -(892 + 65) ;local function v16(v21) if v21 then for v27,v28 in pairs(v21:GetDescendants()) do if v28:IsA("BasePart") then v28.Transparency=2 -1 ;v28.CanCollide=false;elseif (v28:IsA("Decal") or v28:IsA("Texture") or v28:IsA("SurfaceAppearance")) then v28.Transparency=1;end end end end local v17=workspace:FindFirstChild("Map");if v17 then v16(v17:FindFirstChild("Tiles"));v16(v17:FindFirstChild("Vegetation"));v16(v17:FindFirstChild("RoadNetwork"));local v23=v17:FindFirstChild("Props");if v23 then for v34,v35 in pairs(v23:GetChildren()) do if (v35.Name~="ATMs") then v16(v35);end end end end
